//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehber.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONEL()
        {
            this.TBL_PERSONEL1 = new HashSet<TBL_PERSONEL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DEPARTMANID { get; set; }
        public Nullable<int> YONETICIID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TELEFON { get; set; }
        public short MAAS { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public bool CINSIYET { get; set; }
    
        public virtual TBL_DEPARTMAN TBL_DEPARTMAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERSONEL> TBL_PERSONEL1 { get; set; }
        public virtual TBL_PERSONEL TBL_PERSONEL2 { get; set; }
    }
}
