//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehber.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KULLANICI
    {
        public int ID { get; set; }
        public string KULLANICIAD { get; set; }
        public string SIFRE { get; set; }
        public string ROLE { get; set; }
    }
}
